OMNeT++ Simulation Library: cOwnedDynamicExpression Class Reference
cOwnedDynamicExpression Class Reference
Expression Evaluation
#include <cdynamicexpression.h>
Description
An "owned" version cDynamicExpression to allow it to be assigned to module parameters of the type "object".
Public Member Functions
Constructors, destructor, assignment.
cOwnedDynamicExpression (const char *name=nullptr)
cOwnedDynamicExpression (const cOwnedDynamicExpression &other)
cOwnedDynamicExpression & operator= (const cOwnedDynamicExpression &other)=default
Redefined cObject member functions
virtual cOwnedDynamicExpression * dup () const override
virtual std::string str () const override
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)=default
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
virtual std::string getClassAndFullName () const
virtual std::string getClassAndFullPath () const
const cObject * getThisPtr () const
virtual std::ostream & printOn (std::ostream &os) const
virtual bool isSoftOwner () const
virtual void forEachChild (cVisitor *v)
cObject * findObject (const char *name, bool deep=true)
virtual cClassDescriptor * getDescriptor () const
void copyNotSupported () const
Public Member Functions inherited from cDynamicExpression
cDynamicExpression ()
cDynamicExpression (const cDynamicExpression &other)
virtual ~cDynamicExpression ()
cDynamicExpression & operator= (const cDynamicExpression &other)
virtual void parse (const char *text) override
virtual void parse (const char *text, IResolver *resolver)
virtual void parse (const char *text, const std::map< std::string, cValue > &symbolTable)
virtual void setResolver (IResolver *resolver)
virtual IResolver * getResolver () const
virtual void parseNedExpr (const char *text)
virtual cValue evaluate (Context *context) const override
virtual bool boolValue (Context *context) const override
virtual intval_t intValue (Context *context, const char *expectedUnit=nullptr) const override
virtual double doubleValue (Context *context, const char *expectedUnit=nullptr) const override
virtual std::string stringValue (Context *context) const override
virtual cXMLElement * xmlValue (Context *context) const override
virtual cValue evaluate (Context *context) const=0
virtual cValue evaluate (cComponent *contextComponent=nullptr) const
virtual bool boolValue (Context *context) const=0
virtual bool boolValue (cComponent *contextComponent=nullptr) const
virtual intval_t intValue (Context *context, const char *expectedUnit=nullptr) const=0
virtual intval_t intValue (cComponent *contextComponent=nullptr, const char *expectedUnit=nullptr) const
virtual double doubleValue (Context *context, const char *expectedUnit=nullptr) const=0
virtual double doubleValue (cComponent *contextComponent=nullptr, const char *expectedUnit=nullptr) const
virtual std::string stringValue (Context *context) const=0
virtual std::string stringValue (cComponent *contextComponent=nullptr) const
virtual cXMLElement * xmlValue (Context *context) const=0
virtual cXMLElement * xmlValue (cComponent *contextComponent=nullptr) const
virtual int compare (const cExpression *other) const override
virtual bool isAConstant () const override
void setSourceLocation (FileLine loc)
virtual std::string getSourceLocation () const override
Public Member Functions inherited from cExpression
cExpression ()
cExpression (const cExpression &other)=default
virtual ~cExpression ()
cExpression & operator= (const cExpression &other)
virtual cValue evaluate (cComponent *contextComponent=nullptr) const
virtual bool boolValue (cComponent *contextComponent=nullptr) const
virtual intval_t intValue (cComponent *contextComponent=nullptr, const char *expectedUnit=nullptr) const
virtual double doubleValue (cComponent *contextComponent=nullptr, const char *expectedUnit=nullptr) const
virtual std::string stringValue (cComponent *contextComponent=nullptr) const
virtual cXMLElement * xmlValue (cComponent *contextComponent=nullptr) const
Additional Inherited Members
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cSoftOwner * getOwningContext ()
Static Public Member Functions inherited from cDynamicExpression
static double convertUnit (double d, const char *unit, const char *targetUnit)
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Constructor & Destructor Documentation
cOwnedDynamicExpression() [1/2]
cOwnedDynamicExpression (const char * name = nullptr) inline explicit
Constructor.
Referenced by cOwnedDynamicExpression::dup().
cOwnedDynamicExpression() [2/2]
cOwnedDynamicExpression (const cOwnedDynamicExpression & other) inline explicit
Copy constructor.
Member Function Documentation
operator=()
cOwnedDynamicExpression& operator= (const cOwnedDynamicExpression & other) default
Assignment operator. The name member is not copied; see cNamedObject::operator=() for details. Contained objects that are owned by cOwnedDynamicExpression will be duplicated so that the new cOwnedDynamicExpression will have its own copy of them.
dup()
virtual cOwnedDynamicExpression* dup () const inline override virtual
Creates and returns an exact copy of this object.
Reimplemented from cDynamicExpression.
References cOwnedDynamicExpression::cOwnedDynamicExpression().
str()
virtual std::string str () const inline override virtual
Converts the expression to string. See cObject for more details.
Reimplemented from cDynamicExpression.
References cDynamicExpression::str().
The documentation for this class was generated from the following file:
cdynamicexpression.h